security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: bcrypt

        App\Entity\User:
            algorithm: bcrypt

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider

            form_login:
                login_path: login
                check_path: login
                enable_csrf: true
                username_parameter: login[username]
                password_parameter: login[password]
                csrf_parameter: login[csrf]
                use_referer: true

            login_throttling:
                max_attempts: 3
                interval: '15 minutes'

            remember_me:
                remember_me_parameter: login[remember_me]
                secret: '%kernel.secret%'
                lifetime: 86400

            logout:
                path: logout
                target: login

    access_denied_url: /verify

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/(verify|logout), roles: ROLE_USER }
        - { path: ^/(login|register), roles: null }
        - { path: ^/(tv|movie)/\d+/file/\w+, roles: null }
        - { path: ^/, roles: ROLE_VERIFIED }

    hide_user_not_found: true

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: plaintext

            App\Entity\User:
                algorithm: plaintext
