security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: bcrypt

        App\Entity\User:
            algorithm: bcrypt

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider

            form_login:
                login_path: login
                check_path: login
                enable_csrf: true

            login_throttling:
                max_attempts: 3
                interval: '15 minutes'

            remember_me:
                secret: '%env(APP_SECRET)%'
                lifetime: 13800

            logout:
                path: logout
                target: login

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login, roles: null }
        - { path: ^/register, roles: null }
        - { path: ^/movie/\d+/file, roles: null }
        - { path: ^/tv/\d+/file, roles: null }
        - { path: ^/, roles: ROLE_USER }

    hide_user_not_found: true

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: plaintext

            App\Entity\User:
                algorithm: plaintext
