name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  composer:
    name: composer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate composer.json and composer.lock
        run: composer validate --strict

  php-cs-fixer:
    name: PHP-CS Fixer
    runs-on: ubuntu-latest
    needs:
      - composer
    steps:
      - uses: actions/checkout@v2
      - name: Env File
        run: touch .env

      - name: Composer Install
        run: composer install

      - name: php-cs-fix
        run: vendor/bin/php-cs-fixer fix src